
server:
  port: 9000
  error.include-stacktrace: always

spring:
  h2.console.enabled: true
  thymeleaf.cache: false

#  Default H2 configuration
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#
#    jpa.database-platform: org.hibernate.dialect.H2Dialect